#!/bin/bash
#SBATCH --job-name=training
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --output=%x.out
#SBATCH --mem=16GB
#SBATCH --time=4:00:00
#SBATCH --gres=gpu:1

module purge
module load anaconda3/2020.07
eval "$(conda shell.bash hook)"
conda activate env_name
# cd <path_to_your_directory>

python3 dp4.py 1000000 1000
python3 dp4.py 30000000 20

python3 dp5.py 1000000 1000
python3 dp5.py 300000000 20